export const tasksColumn = [
  {
    title: "№",
    dataIndex: "colIndex",
    key: "colIndex",
    width: 40,
    align: "center",
  },
  {
    title: "O'quvchi izohi",
    dataIndex: "description",
    key: "description",
    width: 150,
    align: "center",
  },
  {
    title: "Ustoz izohi",
    dataIndex: "teacherDescription",
    key: "teacherDescription",
    width: 200,
    align: "center",
  },
  {
    title: "Uyga vazifa",
    dataIndex: "HwLink",
    key: "HwLink",
    width: 100,
    align: "center",
  },
  {
    title: "Joylangan",
    dataIndex: "date",
    key: "date",
    width: 100,
    align: "center",
  },
  {
    title: "Holati",
    dataIndex: "status",
    key: "status",
    width: 100,
    align: "center",
  },
  {
    title: "Amallar",
    dataIndex: "actions",
    key: "actions",
    width: 60,
    align: "center",
  },
];
